mysql <<EOFMYSQL
use arpan;
show tables;

DROP TABLE SECTION;
DROP TABLE PROFESSOR;
DROP TABLE COURSE;
DROP TABLE ROOM;
DROP TABLE DEPT;

CREATE TABLE DEPT (
DEPT_CODE char(4),
DEPT_NAME varchar(50) NOT NULL,
ROOM_NUM int NOT NULL,
BUILDING varchar(50) NOT NULL,
PRIMARY KEY(DEPT_CODE)
);
DESC DEPT;

CREATE TABLE PROFESSOR (
PROF_ID int,
PROF_NAME varchar(50) NOT NULL,
DEPT_CODE char(4) NOT NULL,
EMAIL varchar(50) NOT NULL,
PRIMARY KEY(PROF_ID),
FOREIGN KEY (DEPT_CODE) REFERENCES DEPT(DEPT_CODE) ON DELETE CASCADE
);
DESC PROFESSOR;

CREATE TABLE COURSE (
DEPT_CODE CHAR(4) NOT NULL,
COURSE_NUM VARCHAR(5) NOT NULL,
COURSE_NAME VARCHAR(50) NOT NULL,
PRIMARY KEY (DEPT_CODE, COURSE_NUM)
);
DESC COURSE;

CREATE TABLE ROOM (
ROOM_NUM INT NOT NULL,
BUILDING VARCHAR(5) NOT NULL,
CAPACITY INT,
CONSTRAINT ROOM_ID PRIMARY KEY (ROOM_NUM, BUILDING),
CHECK (CAPACITY>0)
);
DESC ROOM;

CREATE TABLE SECTION (
SID INT NOT NULL,
DEPT_CODE CHAR(4) NOT NULL,
COURSE_NUM VARCHAR(5) NOT NULL,
PROF_ID INT NOT NULL,
ROOM_NUM INT NOT NULL,
BUILDING VARCHAR(50) NOT NULL,
DAYS VARCHAR(7),
START_TIME TIME,
END_TIME TIME,
START_DAY DATE NOT NULL,
END_DAY DATE NOT NULL,
MAX_ENROLLMENT INT,
CURRENT_ENROLLMENT INT DEFAULT 0,
PRIMARY KEY(SID),
FOREIGN KEY (DEPT_CODE, COURSE_NUM) REFERENCES COURSE(DEPT_CODE, COURSE_NUM) ON DELETE CASCADE,
FOREIGN KEY (PROF_ID) REFERENCES PROFESSOR(PROF_ID) ON DELETE CASCADE,
FOREIGN KEY (ROOM_NUM, BUILDING) REFERENCES ROOM(ROOM_NUM, BUILDING) ON DELETE CASCADE
);
DESC SECTION;


INSERT INTO DEPT (DEPT_CODE, DEPT_NAME, ROOM_NUM, BUILDING) VALUES ('CSCE', 'Computer Science & Computer Engineering', 504, 'JBHT');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME, ROOM_NUM, BUILDING) VALUES ('ELEG', 'Electrical Engineering', 3217, 'BELL');
INSERT INTO DEPT (DEPT_CODE, DEPT_NAME, ROOM_NUM, BUILDING) VALUES ('MEEG', 'Mechanical Engineering', 204, 'MEEG');
SELECT * FROM DEPT;

INSERT INTO PROFESSOR (PROF_ID, PROF_NAME, DEPT_CODE, EMAIL) VALUES (123456, 'Susan Gauch', 'CSCE', 'sgauch@uark.edu');
INSERT INTO PROFESSOR (PROF_ID, PROF_NAME, DEPT_CODE, EMAIL) VALUES (123457, 'John Gauch', 'CSCE', 'jgauch@uark.edu');
INSERT INTO PROFESSOR (PROF_ID, PROF_NAME, DEPT_CODE, EMAIL) VALUES (222222, 'Lora Strother', 'CSCE', 'lstrothe@uark.edu');
INSERT INTO PROFESSOR (PROF_ID, PROF_NAME, DEPT_CODE, EMAIL) VALUES (010101, 'Wing Ning Li', 'CSCE', 'wingning@uark.edu');
INSERT INTO PROFESSOR (PROF_ID, PROF_NAME, DEPT_CODE, EMAIL) VALUES (444555, 'Alexander Nelson', 'CSCE', 'ahnelson@uark.edu');
SELECT * FROM PROFESSOR;

INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '2004', 'Programming Foundations I');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '2114', 'Programming Foundations II');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '3193', 'Programming Paradigms');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '3139H', 'Honors Programming Paradigms');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '4553', 'Information Retrieval');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '4263', 'Mobile Programming');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '4623', 'Advanced Data Structures');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '4963', 'Capstone II');
INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '5533', 'Advanced Information Retrieval');
SELECT * FROM COURSE;

INSERT INTO ROOM (ROOM_NUM, BUILDING, CAPACITY) VALUES (239, 'JBHT', 36);
INSERT INTO ROOM (ROOM_NUM, BUILDING, CAPACITY) VALUES (236, 'JBHT', 45);
INSERT INTO ROOM (ROOM_NUM, BUILDING, CAPACITY) VALUES (147, 'JBHT', 140);
INSERT INTO ROOM (ROOM_NUM, BUILDING, CAPACITY) VALUES (216, 'JBHT', 170);
INSERT INTO ROOM (ROOM_NUM, BUILDING, CAPACITY) VALUES (2269, 'BELL', 70);
INSERT INTO ROOM (ROOM_NUM, BUILDING, CAPACITY) VALUES (2286, 'BELL', 100);
SELECT * FROM ROOM;


INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (9597, 'CSCE', '2004', 222222, 2269, 'BELL',	'MWF', '15:05',	'15:55', '2023-08-01',	'2023-07-12', 70, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (1449, 'CSCE', '2114', 123457, 216, 'JBHT',	'MWF', '12:55',	'13:45', '2023-08-01',	'2023-07-12', 138, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (2930, 'CSCE', '3193', 222222, 216, 'JBHT',	'TR', '15:30',	'16:45', '2023-08-01',	'2023-07-12', 140, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (4636, 'CSCE', '3139H', 222222, 216, 'JBHT',	'TR', '15:30',	'16:45', '2023-08-01',	'2023-07-12', 30, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (12550, 'CSCE', '4553', 123456, 239, 'JBHT',	'MWF', '9:40',	'10:30', '2023-08-01',	'2023-07-12', 30, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (11957, 'CSCE', '4263', 010101, 239, 'JBHT',	'TR', '8:00',	'9:15', '2023-08-01',	'2023-07-12', 0, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (6704, 'CSCE', '4623', 444555, 2286, 'BELL',	'MWF', '10:45',	'11:35', '2023-08-01',	'2023-07-12', 65, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (6325, 'CSCE', '4963', 444555, 147, 'JBHT',	'MWF', '15:05',	'15:55', '2023-08-01',	'2023-07-12', 50, 0);
INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, DAYS, START_TIME, END_TIME, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT) 
VALUES (11944, 'CSCE', '5533', 123456, 239, 'JBHT',	'MWF', '15:05',	'15:55', '2023-08-01',	'2023-07-12', 30, 0);
SELECT * FROM SECTION;

SELECT * FROM ROOM WHERE CAPACITY = (SELECT MAX(CAPACITY) FROM ROOM);

SELECT c.COURSE_NUM, c.DEPT_CODE, (s.MAX_ENROLLMENT - s.CURRENT_ENROLLMENT) AS seats_available
FROM COURSE c
INNER JOIN SECTION s ON c.DEPT_CODE = s.DEPT_CODE AND c.COURSE_NUM = s.COURSE_NUM
WHERE c.COURSE_NUM >= '4000' AND s.CURRENT_ENROLLMENT < s.MAX_ENROLLMENT;
SELECT p.PROF_NAME, SUM(s.MAX_ENROLLMENT) AS total_students
FROM PROFESSOR p
INNER JOIN SECTION s ON p.PROF_ID = s.PROF_ID
GROUP BY p.PROF_NAME;

SELECT p.PROF_NAME, d.DEPT_NAME, d.BUILDING
FROM PROFESSOR p
INNER JOIN DEPT d ON p.DEPT_CODE = d.DEPT_CODE
WHERE NOT EXISTS (
  SELECT *
  FROM SECTION s
  INNER JOIN COURSE c ON s.DEPT_CODE = c.DEPT_CODE AND s.COURSE_NUM = c.COURSE_NUM
  INNER JOIN ROOM r ON s.BUILDING = r.BUILDING AND s.ROOM_NUM = r.ROOM_NUM
  WHERE s.PROF_ID = p.PROF_ID AND d.BUILDING <> r.BUILDING
);

INSERT INTO COURSE (DEPT_CODE, COURSE_NUM, COURSE_NAME) VALUES ('CSCE', '4013', 'Computer Graphics');

INSERT INTO SECTION (SID, DEPT_CODE, COURSE_NUM, PROF_ID, ROOM_NUM, BUILDING, START_DAY, END_DAY,  MAX_ENROLLMENT, CURRENT_ENROLLMENT)
VALUES (2023, 'CSCE', '4013', 123457, 239, 'JBHT', '2023-08-21', '2023-12-07', 25, 0);

SELECT s.*
FROM SECTION s
JOIN PROFESSOR p ON s.PROF_ID = p.PROF_ID
WHERE p.PROF_NAME = 'John Gauch';

UPDATE SECTION SET CURRENT_ENROLLMENT = 100 WHERE COURSE_NUM = '2004';

SELECT * FROM SECTION WHERE COURSE_NUM = '2004';

SELECT COURSE.COURSE_NUM, COURSE.COURSE_NAME, PROFESSOR.PROF_NAME 
FROM COURSE 
INNER JOIN SECTION ON COURSE.DEPT_CODE = SECTION.DEPT_CODE AND COURSE.COURSE_NUM = SECTION.COURSE_NUM 
INNER JOIN PROFESSOR ON SECTION.PROF_ID = PROFESSOR.PROF_ID 
WHERE COURSE.COURSE_NUM LIKE '4%';

DELETE FROM PROFESSOR WHERE PROF_ID = 010101;

SELECT COURSE.COURSE_NUM, COURSE.COURSE_NAME, PROFESSOR.PROF_NAME 
FROM COURSE 
INNER JOIN SECTION ON COURSE.DEPT_CODE = SECTION.DEPT_CODE AND COURSE.COURSE_NUM = SECTION.COURSE_NUM 
INNER JOIN PROFESSOR ON SECTION.PROF_ID = PROFESSOR.PROF_ID 
WHERE COURSE.COURSE_NUM LIKE '4%';

EOFMYSQL
